config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :issues, except: [:index, :show, :destroy] do
    member do
      post :vote
      post :acknowledge
      post :close
    end
  end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  PRIORITY_LEVELS = (1..6).to_a

  belongs_to :owner, class_name: 'User'
  belongs_to :closer, class_name: 'User'

  has_and_belongs_to_many :voters, class_name: 'User'

  scope :opened, -> { where(closer_id: nil) }
  scope :closed, -> { where.not(closer_id: nil) }

  validates :statement, presence: true
  validates :priority, inclusion: {in: PRIORITY_LEVELS}
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  has_many :reported_issues, class_name: 'Issue', foreign_key: 'owner_id'
  has_and_belongs_to_many :issues_voted_for, class_name: 'Issue'

  def can_acknowledge_issue?(issue)
    self.admin?
  end

  def can_manage_issue?(issue)
    (self == issue.andand.owner) || self.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @open_issues = Issue.opened.order('priority ASC')
    @closed_issues = Issue.closed.order('updated_at DESC')
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: [:edit, :update, :vote, :acknowledge, :close]
  before_action :prevent_unauthorized_acknowledgement, only: [:acknowledge]
  before_action :prevent_unauthorized_managing, only: [:edit, :update, :close]

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params.merge(owner: current_user))

    respond_to do |format|
      if @issue.save
        format.html { redirect_to root_path, notice: 'Issue was successfully created.' }
        format.json { render :index, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to root_path, notice: 'Issue was successfully updated.' }
        format.json { render :index, status: :ok, location: root_path }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /issues/1/vote
  # POST /issues/1/vote.json
  def vote
    respond_to do |format|
      unless @issue.voters.include? current_user
        @issue.voters << current_user
        format.html { redirect_to root_path, notice: 'Your vote has been successfully cast.' }
        format.json { render :index, status: :ok, location: root_path }
      else
        format.html { redirect_to root_path, notice: 'Issue cannot be voted for more than once.' }
        format.json { render status: :forbidden, nothing: true }
      end
    end
  end

  # POST /issues/1/acknowledge
  # POST /issues/1/acknowledge.json
  def acknowledge
    respond_to do |format|
      if @issue.update acknowledged: true
        format.html { redirect_to root_path, notice: 'Issue acknowledged.' }
        format.json { render :index, status: :ok, location: root_path }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /issues/1/close
  # POST /issues/1/close.json
  def close
    respond_to do |format|
      if @issue.update closer: current_user
        format.html { redirect_to root_path, notice: 'Issue was successfully closed.' }
        format.json { render :index, status: :ok, location: root_path }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:statement, :priority)
    end

    # Renders a 403 if the user acknowledging the issue is not authorized to do so.
    def prevent_unauthorized_acknowledgement
      unless current_user.can_acknowledge_issue? @issue
        render status: :forbidden, nothing: true
      end
    end

    # Renders a 403 if the user managing the issue is not authorized to do so.
    def prevent_unauthorized_managing
      unless current_user.can_manage_issue? @issue
        render status: :forbidden, nothing: true
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=24&d=mm&r=pg"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper

  def options_for_priorities
    Issue::PRIORITY_LEVELS.map do |priority|
      [t("activerecord.attribute_values.issue.priority.#{priority}"), priority]
    end
  end

  def class_for_priority(priority:)
    case priority
    when 1
      'priority-1'
    when 2
      'priority-2'
    when 3
      'priority-3'
    when 4
      'priority-4'
    when 5
      'priority-5'
    when 6
      'priority-brandon'
    else
      ''
    end
  end

end

app/views/home/index.html.haml
%h1 Reported Issues

%h2 Open Issues

%table.table.table-striped
  %thead
    %tr
      %th Issue
      %th Acknowledged
      %th Priority Level
      %th Reported By
      %th Votes
      - if user_signed_in?
        %th
        %th

  %tbody
    - @open_issues.each do |issue|
      %tr{class: class_for_priority(priority: issue.priority)}
        %td= issue.statement
        %td= issue.acknowledged
        %td= t("activerecord.attribute_values.issue.priority.#{issue.priority}")
        %td
          = image_tag gravatar_url(current_user)
          = issue.owner.andand.email
        %td= issue.voters.count
        - if user_signed_in? && !current_user.issues_voted_for.include?(issue)
          %td= link_to 'Vote for Issue', vote_issue_path(issue), method: :post
        - else
          %td

        - if user_signed_in? && current_user.can_acknowledge_issue?(issue) && !issue.acknowledged?
          %td= link_to 'Acknowledge', acknowledge_issue_path(issue), method: :post
        - else
          %td

        - if user_signed_in? && current_user.can_manage_issue?(issue)
          %td= link_to 'Edit', edit_issue_path(issue)
          %td= link_to 'Close', close_issue_path(issue), method: :post, data: { confirm: 'Are you sure?' }
        - else
          %td
          %td

%h2 Closed Issues

%table.table.table-striped
  %thead
    %tr
      %th Issue
      %th Acknowledged
      %th Priority Level
      %th Closed By

  %tbody
    - @closed_issues.each do |issue|
      %tr{class: class_for_priority(priority: issue.priority)}
        %td= issue.statement
        %td= issue.acknowledged
        %td= t("activerecord.attribute_values.issue.priority.#{issue.priority}")
        %td
          = image_tag gravatar_url(current_user)
          = issue.closer.andand.email

%br

- if user_signed_in?
  = link_to 'New Issue', new_issue_path

app/views/issues/_form.html.haml
= form_for @issue do |f|
  - if @issue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :statement
    = f.text_field :statement, class: 'form-control'
  .form-group
    = f.label :priority
    = f.select :priority, options_for_priorities, include_blank: true, class: 'form-control'

  .actions
    = f.submit 'Save', class: 'btn btn-default'

app/views/issues/edit.html.haml
%h1 Editing issue

= render 'form'

= link_to 'Show', @issue
\|
= link_to 'Back', root_path

app/views/issues/new.html.haml
%h1 New issue

= render 'form'

= link_to 'Back', root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}/
    %title Blomme
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header= link_to 'Does Brandon Know?', root_path, class: 'navbar-brand'
        %div
          %ul.nav.navbar-nav.navbar-right
            %li
              - if user_signed_in?
                %a{href: '#'}= "Logged in as #{current_user.email}"
              - else
                = link_to 'Log In', new_user_session_path
            - if user_signed_in?
              %li
                %a{href: '#'}= image_tag gravatar_url(current_user)
            %li
              %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', href: '#', role: 'button'}
                %span.glyphicon.glyphicon-menu-hamburger{'aria-hidden' => 'true'}
              %ul.dropdown-menu
                %li= link_to 'Account', edit_user_registration_path
                - if user_signed_in? && current_user.admin?
                  %li= link_to 'Admin', rails_admin_path
                %li.divider{role: 'separator'}
                %li= link_to 'Log Out', destroy_user_session_path, method: :delete

    - if notice
      %p.notice= notice
    - if alert
      %p.alert= alert

    = yield